import { InMemoryCache } from "@apollo/client";
import { concatPagination } from "@apollo/client/utilities";
// generated by Fragment Matcher plugin
import introspectionResult from "../api/gql/fragment-matcher";

export const cache: InMemoryCache = new InMemoryCache({
  possibleTypes: introspectionResult.possibleTypes,
  typePolicies: {
    Query: {
      fields: {
        allPosts: concatPagination(),
      },
    },
  },
});
